
language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.6
    - 7.1

sudo: false

branches:
    only:
        - master
        - /^\d+\.\d+$/

env:
    - EZ_KERNEL_VERSION=^6.0

matrix:
    include:
        - php: 7.1
          env: EZ_KERNEL_VERSION=^6.9

install:
    - echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer require "ezsystems/ezpublish-kernel:${EZ_KERNEL_VERSION}" --no-update
    - composer install

notification:
  email: false

script:
- ./vendor/bin/phpunit --colors -c phpunit.xml --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash) 

