services:
  ezsystems.calameobundle.fieldtype.ezcalameo:
    parent: ezpublish.fieldType
    class: CalameoBundle\FieldType\Calameo\Type
    tags:
    - {name: ezpublish.fieldType, alias: ezcalameo}
    - {name: ezpublish.fieldType.nameable, alias: ezcalameo}
    arguments:
      - '@ezsystems.calameobundle.calameo.client'

  ezpublish.fieldType.indexable.ezcalameo:
    class: CalameoBundle\FieldType\Calameo\SearchField
    tags:
    - {name: ezpublish.fieldType.indexable, alias: ezcalameo}