services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  CalameoBundle\Calameo\Client:
    arguments:
      - '%calameo%'

  ezsystems.calameobundle.calameo.client:
    alias: CalameoBundle\Calameo\Client

  CalameoBundle\Twig\CalameoRuntime: ~

  CalameoBundle\Twig\CalameoExtension:
    tags: ['twig.extension']

