services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  CalameoBundle\Calameo\Gateway:
    arguments:
      $cache: '@ezpublish.cache_pool'

  CalameoBundle\Calameo\Client:
    arguments:
      - '%calameo%'


  ezsystems.calameobundle.calameo.client:
    alias: CalameoBundle\Calameo\Client

  CalameoBundle\Twig\CalameoRuntime: ~

  CalameoBundle\Twig\CalameoExtension:
    tags: ['twig.extension']

  ezsystems.calameobundle.fieldtype.ezcalameo.converter:
    class: CalameoBundle\FieldType\Calameo\LegacyConverter
    tags:
      - {name: ezpublish.storageEngine.legacy.converter, alias: ezcalameo}
