<?php
/**
 * Created by PhpStorm.
 * User: jlchassaing
 * Date: 05/10/2018
 * Time: 09:56
 */

namespace CalameoBundle;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class CalameoBundle extends Bundle
{
    public function build( ContainerBuilder $container )
    {
        parent::build( $container ); // TODO: Change the autogenerated stub
    }


}